### ISSUE TITLE
Is the group's demo still accessible?

### ISSUE THREAD

**Issue by Scott20222** [arj03/groupies#1]
https://between-two-worlds.dk/groupies/   This demo seems to be inaccessible, is it closed?
                                                                                                                        thanks

**Comment by arj03** [comment]
I took down that server sadly

**Comment by Scott20222** [comment]
Why is it closed? The group function is very useful. Is there any problem?

**Comment by arj03** [comment]
I didn't know anyone was using it ;)

There was a problem with the vps and I didn't want to bother keeping it updated anymore. I'm waiting for [go-ssb-room](https://github.com/ssb-ngi-pointer/go-ssb-room/pull/291) to work on arm so I can run in on a pi.

**Comment by Scott20222** [comment]
The group function of your browser is really useful. We have tested the function, and now we have built go-ssb-room. I want to try it again. Is there a plug-in that can be installed directly?thanks

**Comment by arj03** [comment]
You can just `npm run build` the repo and copy the `dist/` to some webserver and it should work.

This should probably be changed to your room:

https://github.com/arj03/groupies/blob/09240ac4725fac1d0d1b2c2914ac637fad67de34/index.js#L348

**Comment by Scott20222** [comment]
ok,thanks for your guidance.
